"use client";
import { useState } from "react";
import { Loader2, RefreshCw } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { useCitizenDuplicateFlagsQuery } from "@/hooks";
export default function DuplicatesPage(){ const [page,setPage]=useState(1); const q=useCitizenDuplicateFlagsQuery({page,per_page:10,status:"open"}); const rows=q.data?.data??[]; const meta=q.data?.meta; return <div className="space-y-6"><div className="flex justify-between"><div><h1 className="text-2xl font-bold">Duplicate Alerts</h1><p className="text-muted-foreground">Review possible duplicate registrations.</p></div><Button variant="outline" onClick={()=>q.refetch()}><RefreshCw className="mr-2 h-4 w-4"/>Refresh</Button></div><Card><CardHeader><CardTitle>Open Flags</CardTitle></CardHeader><CardContent>{q.isLoading?<div className="flex justify-center py-10"><Loader2 className="mr-2 h-4 w-4 animate-spin"/>Loading...</div>:<Table><TableHeader><TableRow><TableHead>Citizen</TableHead><TableHead>Matched Citizen</TableHead><TableHead>Reason</TableHead><TableHead>Status</TableHead><TableHead>Flagged</TableHead></TableRow></TableHeader><TableBody>{rows.length===0?<TableRow><TableCell colSpan={5} className="py-8 text-center">No duplicate flags.</TableCell></TableRow>:rows.map((flag)=><TableRow key={flag.id}><TableCell>{flag.citizen?.full_name ?? flag.citizen_id}</TableCell><TableCell>{flag.matched_citizen?.full_name ?? flag.matched_citizen_id ?? "—"}</TableCell><TableCell>{flag.remarks ?? [flag.national_id, flag.phone].filter(Boolean).join(" / ")}</TableCell><TableCell><Badge>{flag.status ?? "open"}</Badge></TableCell><TableCell>{flag.flagged_at ? new Date(flag.flagged_at).toLocaleString() : "—"}</TableCell></TableRow>)}</TableBody></Table>}{meta&&meta.last_page>1&&<div className="mt-4 flex justify-between"><span>Page {meta.current_page} of {meta.last_page}</span><div className="flex gap-2"><Button size="sm" variant="outline" disabled={page<=1} onClick={()=>setPage(p=>p-1)}>Previous</Button><Button size="sm" variant="outline" disabled={page>=meta.last_page} onClick={()=>setPage(p=>p+1)}>Next</Button></div></div>}</CardContent></Card></div> }
