import type { CitizenItem, PaginatedResponse, PaginationMeta } from "@/types/citizen/citizen.type";
import type { OfficeItem } from "@/types/location/office.type";
export type HouseholdStatus = "active" | "inactive" | "suspended";
export type HouseholdPayload = { head_citizen_id: number | string; city_id: number | string; subcity_id: number | string; woreda_id: number | string; zone_id: number | string; house_number?: string; address?: string; status?: HouseholdStatus };
export type HouseholdMemberPayload = { citizen_id?: number | string; relationship: string; is_dependent?: boolean; joined_at?: string; left_at?: string | null; status?: "active" | "inactive" };
export type HouseholdMemberItem = { id: number; household_id: number; citizen_id: number; citizen?: CitizenItem | null; relationship: string; is_head: boolean; is_dependent: boolean; joined_at?: string | null; left_at?: string | null; status: string };
export type HouseholdItem = { id: number; household_number: string; head_citizen_id: number; head_citizen?: CitizenItem | null; city_id?: number; subcity_id?: number; woreda_id?: number; zone_id?: number; city?: OfficeItem | null; subcity?: OfficeItem | null; woreda?: OfficeItem | null; zone?: OfficeItem | null; house_number?: string | null; address?: string | null; status: HouseholdStatus; members_count?: number; members?: HouseholdMemberItem[]; created_at?: string; updated_at?: string };
export type HouseholdListParams = { search?: string; status?: HouseholdStatus | "all"; city_id?: number | string; subcity_id?: number | string; woreda_id?: number | string; zone_id?: number | string; page?: number; per_page?: number };
export type CitizenProfile = CitizenItem & { household?: HouseholdItem | null; household_memberships?: HouseholdMemberItem[]; property_placeholder?: { message: string } };
export type NotificationItem = { id: number; title: string; message: string; type?: string; read_at?: string | null; created_at?: string };
export type CitizenDashboardMetrics = { total_households: number; total_registered_citizens: number; active_citizens: number; pending_verifications: number; escalated_cases: number; duplicate_alerts: number; suspended_citizens: number; household_statistics?: Record<string, unknown> };
export type CitizenReportParams = { from_date?: string; to_date?: string; city_id?: number | string; subcity_id?: number | string; woreda_id?: number | string; zone_id?: number | string };
export type { PaginatedResponse, PaginationMeta };
