export {
  useUsersQuery,
  useUserQuery,
  useRolesLiteQuery,
  useRolesLiteQuery as useUserRolesLiteQuery,
  useOfficesLiteQuery,
  useCreateUserMutation,
  useUpdateUserMutation,
  useDeleteUserMutation,
  useToggleUserMutation,
  useResetUserPasswordMutation,
  useAssignUserRoleMutation,
  useRolesQuery,
  useCreateRoleMutation,
  useUpdateRoleMutation,
  useAvailableRolePermissionsQuery,
  useRolePermissionsQuery,
  useAssignRolePermissionsMutation,
  usePermissionsQuery,
  useAllPermissionsQuery,
  useCreatePermissionMutation,
  useUpdatePermissionMutation,
  useDeletePermissionMutation,
} from "@/hooks/user/use-users";

export {
  useCitizensQuery,
  useCitizenQuery,
  useCreateCitizenMutation,
  useUpdateCitizenMutation,
  useDeleteCitizenMutation,
  useSubmitCitizenMutation,
  useUploadCitizenDocumentMutation,
  useDeleteCitizenDocumentMutation,
  useDuplicateCitizenMutation,
  useCitizenWorkflowQueueQuery,
  useCitizenWorkflowQuery,
  useCitizenDuplicateFlagsQuery,
  useStartCitizenReviewMutation,
  useVerifyCitizenDocumentsMutation,
  useWoredaVerifyCitizenMutation,
  useSubcityApproveCitizenMutation,
  useGenerateCitizenIdMutation,
  useActivateCitizenMutation,
  useRejectCitizenMutation,
  useFlagCitizenMutation,
  useSuspendCitizenMutation,
} from "@/hooks/citizen/use-citizens";

export {
  useOfficesQuery,
  useAllOfficesQuery,
  useOfficeTreeQuery,
  useOfficeQuery,
  useCreateOfficeMutation,
  useUpdateOfficeMutation,
  useToggleOfficeMutation,
  useDeleteOfficeMutation,
} from "@/hooks/location/use-offices";

export { useAuditLogsQuery } from "@/hooks/user/use-audit-logs";
