"use client";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { toast } from "sonner";
import { citizenService } from "@/services/citizen/citizen.service";
import type { CitizenListParams, CitizenPayload, CitizenWorkflowListParams, DocumentVerificationPayload, DuplicateCheckPayload, WorkflowActionPayload } from "@/types/citizen/citizen.type";
export const citizenKeys = { all: ["citizens"] as const, list: (p: CitizenListParams = {}) => ["citizens", "list", p] as const, detail: (id: number | string) => ["citizens", "detail", id] as const, workflowQueue: (p: CitizenWorkflowListParams = {}) => ["citizens", "workflow-queue", p] as const, workflow: (id: number | string) => ["citizens", "workflow", id] as const, duplicateFlags: (p: Record<string, unknown> = {}) => ["citizens", "duplicate-flags", p] as const };
function inv(qc: ReturnType<typeof useQueryClient>, id?: number | string) { qc.invalidateQueries({ queryKey: citizenKeys.all }); if (id) { qc.invalidateQueries({ queryKey: citizenKeys.detail(id) }); qc.invalidateQueries({ queryKey: citizenKeys.workflow(id) }); } }
export function useCitizensQuery(params: CitizenListParams = {}) { return useQuery({ queryKey: citizenKeys.list(params), queryFn: () => citizenService.list(params) }); }
export function useCitizenQuery(id?: number | string) { return useQuery({ queryKey: citizenKeys.detail(id ?? ""), queryFn: () => citizenService.show(id as number | string), enabled: Boolean(id) }); }
export function useCreateCitizenMutation(onSuccess?: (id?: number | string) => void) { const qc = useQueryClient(); return useMutation({ mutationFn: (payload: CitizenPayload) => citizenService.create(payload), onSuccess: (data: any) => { inv(qc); toast.success("Citizen created"); onSuccess?.(data?.id); } }); }
export function useUpdateCitizenMutation(onSuccess?: () => void) { const qc = useQueryClient(); return useMutation({ mutationFn: ({ id, payload }: { id: number | string; payload: CitizenPayload }) => citizenService.update(id, payload), onSuccess: (_d, v) => { inv(qc, v.id); toast.success("Citizen updated"); onSuccess?.(); } }); }
export function useDeleteCitizenMutation(onSuccess?: () => void) { const qc = useQueryClient(); return useMutation({ mutationFn: (id: number | string) => citizenService.remove(id), onSuccess: () => { inv(qc); toast.success("Citizen deleted"); onSuccess?.(); } }); }
export function useSubmitCitizenMutation(onSuccess?: () => void) { const qc = useQueryClient(); return useMutation({ mutationFn: (id: number | string) => citizenService.submit(id), onSuccess: (_d, id) => { inv(qc, id); toast.success("Citizen submitted"); onSuccess?.(); } }); }
export function useUploadCitizenDocumentMutation(onSuccess?: () => void) { const qc = useQueryClient(); return useMutation({ mutationFn: ({ id, payload }: { id: number | string; payload: Parameters<typeof citizenService.uploadDocument>[1] }) => citizenService.uploadDocument(id, payload), onSuccess: (_d, v) => { inv(qc, v.id); toast.success("Document uploaded"); onSuccess?.(); } }); }
export function useDeleteCitizenDocumentMutation(onSuccess?: () => void) { const qc = useQueryClient(); return useMutation({ mutationFn: ({ id, documentId }: { id: number | string; documentId: number | string }) => citizenService.deleteDocument(id, documentId), onSuccess: (_d, v) => { inv(qc, v.id); toast.success("Document deleted"); onSuccess?.(); } }); }
export function useDuplicateCitizenMutation() { return useMutation({ mutationFn: (payload: DuplicateCheckPayload) => citizenService.checkDuplicates(payload) }); }
export function useCitizenWorkflowQueueQuery(params: CitizenWorkflowListParams = {}) { return useQuery({ queryKey: citizenKeys.workflowQueue(params), queryFn: () => citizenService.workflowQueue(params) }); }
export function useCitizenWorkflowQuery(id?: number | string) { return useQuery({ queryKey: citizenKeys.workflow(id ?? ""), queryFn: () => citizenService.workflow(id as number | string), enabled: Boolean(id) }); }
export function useCitizenDuplicateFlagsQuery(params: { status?: string; page?: number; per_page?: number } = {}) { return useQuery({ queryKey: citizenKeys.duplicateFlags(params), queryFn: () => citizenService.duplicateFlags(params) }); }
function workflowMutation(name: string, fn: (id: number | string, payload?: WorkflowActionPayload) => Promise<unknown>) { return function useWorkflowMutation(onSuccess?: () => void) { const qc = useQueryClient(); return useMutation({ mutationFn: ({ id, payload }: { id: number | string; payload?: WorkflowActionPayload }) => fn(id, payload), onSuccess: (_d, v) => { inv(qc, v.id); toast.success(name); onSuccess?.(); } }); }; }
export const useStartCitizenReviewMutation = workflowMutation("Review started", citizenService.startReview);
export const useWoredaVerifyCitizenMutation = workflowMutation("Woreda verification completed", citizenService.woredaVerify);
export const useSubcityApproveCitizenMutation = workflowMutation("Subcity approval completed", citizenService.subcityApprove);
export const useGenerateCitizenIdMutation = workflowMutation("Citizen ID generated", citizenService.generateId);
export const useActivateCitizenMutation = workflowMutation("Citizen activated", citizenService.activate);
export const useRejectCitizenMutation = workflowMutation("Citizen rejected", citizenService.reject);
export const useFlagCitizenMutation = workflowMutation("Citizen flagged", citizenService.flag);
export const useSuspendCitizenMutation = workflowMutation("Citizen suspended", citizenService.suspend);
export function useVerifyCitizenDocumentsMutation(onSuccess?: () => void) { const qc = useQueryClient(); return useMutation({ mutationFn: ({ id, payload }: { id: number | string; payload?: DocumentVerificationPayload }) => citizenService.verifyDocuments(id, payload ?? {}), onSuccess: (_d, v) => { inv(qc, v.id); toast.success("Documents verified"); onSuccess?.(); } }); }
